### ISSUE TITLE
Add ?players command to Discord

### ISSUE THREAD

**Issue by Spoffy** [Spoffy/EcoDiscordPlugin#4]
Listing online players on the Eco server.

**Comment by Pretmaker** [comment]
This seems to be added, but since ECO 7.3.0 it doesn't clear the player from the list once he leaves ECO. It will stay in the list until the server or plugin is reloaded it seems. Didn't have time yet to enable debug logging for this though. So I only have STR which work on my server. Maybe someone else can confirm this issue exists on other servers also?

**Comment by Spoffy** [comment]
I've fixed this in the code, and it'll be a part of the next release! :)
